# Generated by Django 4.2.27 on 2025-12-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_score', models.FloatField(default=0.0)),
                ('raw_percent', models.FloatField(default=0.0)),
                ('capped_percent', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('feedback_profile', models.TextField(blank=True, null=True)),
                ('feedback_category_detail', models.TextField(blank=True, null=True)),
                ('feedback_recommended_actions', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.JSONField()),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_readiness.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='ai_readiness.question')),
            ],
            options={
                'indexes': [models.Index(fields=['assessment', 'question'], name='ai_readines_assessm_0c4c1b_idx')],
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
